django-backend/src/Users/urls.py
from django.urls  import path

from .views import * 

from django.urls import path
from . import views

app_name = 'Users'

urlpatterns = [
    path('login/', views.user_login, name = 'login-main'),
    path('logout/', views.user_logout, name = 'logout-main'),
    path('register/', views.user_register, name = 'register'), 
    path('confirm-email/<uuid:token>/', views.confirm_email, name='confirm-email'),
    path('profile/', views.profile, name = 'profile'),
    path('edit/', views.edit_profile, name = 'profile-edit')
    
]

django-backend/src/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FilmView.as_view(), name = "home"),
    path('search/', views.Search.as_view(), name='search'), 
    path('filter/', views.Filtr, name='filter'),
    path('search_navbar/', views.search_navbar, name = 'search_navbar'),
    path('films/<int:kinopoisk_id>/', views.film, name = 'film'),
    path('watch-later/<int:kinopoisk_id>/', views.watch_later, name = 'watch_later'),
    path('films-watch/', views.Film_watch , name='films-watch'),
    path('add-comment/<int:kinopoisk_id>/', views.add_comment, name='add_comment'),
    path('remove-comment/<int:kinopoisk_id>/<int:comment_id>',  views.remove_comment, name='remove_comment')

] 

django-backend/src/online_streaming/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Users.urls')),
    path('api/', include('core.api.urls')),
    path('', include('core.urls')),

    
]  + debug_toolbar_urls() 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root = settings.MEDIA_ROOT)

django-backend/src/Users/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
	username = models.CharField(max_length=32, unique=True)
	email = models.EmailField(unique=True)
	USERNAME_FIELD = 'username'
	REQUIRED_FIELDS = ['email']

class EmailToken(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	token = models.UUIDField(default= uuid.uuid4() ,unique= True)
	created_at = models.DateTimeField(auto_now_add=True)

django-backend/src/Users/forms.py
from django import forms
from .models import User
class LoginUser(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterUser(forms.Form):
    email = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        data =  super().clean()
        password1 = data.get('password1')
        password2 = data.get('password2')

        if password1 and password2 and password1 == password2:
            return data
        
        else:
            return forms.ValidationError('No good')
        

class EditUser(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    

django-backend/src/Users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from .forms import LoginUser, RegisterUser, EditUser
from .models import User, EmailToken
from .tasks_celery import sending_email
from django.contrib import messages
from django.contrib.auth.decorators import login_required

def user_login(request):
    if request.method == 'POST':
        form = LoginUser(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                form.add_error(None, 'Invalid username or password') 
    else:
        form = LoginUser()
    
    return render(request, 'sigin.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('home')


def user_register(request):
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            try:
                user  = User.objects.create_user(
                    username=cd['username'],
                    email=cd['email'],
                    password=cd['password1']
                )
                user.is_active = True
                user.save()
                
                token = EmailToken.objects.create(user=user)
                link_activate = request.build_absolute_uri(reverse('confirm-email', args=[str(token.token)]))
                sending_email.delay(link=link_activate, email_user=user.email)

                messages.success(request, f"Письмо успешно отправлено на почту {user.email}!")
                return redirect('register')
            except Exception as e:
                form.add_error(None, f'Error during registration: {str(e)}') 
    else:
        form = RegisterUser()
    
    return render(request, 'register.html', {'form': form})


def confirm_email(request, token):
    confirm_token = get_object_or_404(EmailToken, token=token)
    user = confirm_token.user
    user.is_active = True
    user.save()
    confirm_token.delete()
    login(request, user)
    
    return redirect('home')


@login_required
def profile(request):
    user = request.user
    return render(request, 'profile.html', {"profile":user})

@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = EditUser(request.POST)
        user = request.user
        if form.is_valid():
            cd = form.cleaned_data
            user.first_name = cd['first_name']
            user.last_name = cd['last_name'] 
            user.save()
        return redirect('Users:profile') 

    else: 
        form = EditUser()
    return render(request, 'profile_edit.html', {'form':form})

django-backend/src/Users/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{profile.username}} </p>
    <p>{{profile.email}}</p>
    <p>{{profile.first_name}}</p>
    <p>{{profile.last_name}}</p>
    <a href="{% url 'Users:profile-edit' %}">Изменить профиль</a>
</body>
</html>

django-backend/src/Users/templates/profile_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редактирование</title>
</head>
<body>
  
            <h1>Редактирование</h1>
  
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Сохранить изменения</button>
            </form>
  
        <a href="{% url 'Users:profile' %}">Назад</a>
  
</body>
</html>

django-backend/src/Users/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Streaming Service</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div class="container">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form class="login-form" method="POST">
        {% csrf_token %}
            <h1>Регистрация</h1>
            <div class="form-input">
                <input type="text" id="email" name="email" class="form-control" required placeholder=" " autocomplete="off" />
                <label for="email">Почта</label>
            </div>
            <div class="form-input">
                <input type="text" id="username" name="username" class="form-control" required placeholder=" " autocomplete="off" />
                <label for="username">Логин</label>
            </div>
            <div class="form-input">
                <input type="password" id="password1" name="password1" class="form-control" required placeholder=" " autocomplete="off" />
                <label for="password1">Пароль</label>
            </div>
            <div class="form-input">
                <input type="password" id="password2" name="password2" class="form-control" required placeholder=" " autocomplete="off" />
                <label for="password2">Повторно пароль</label>
            </div>
            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>
</body>
</html>

django-backend/src/Users/templates/sigin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Streaming Service</title>
  <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>

    <form class="login-form" method="POST">
    {% csrf_token %}
      <h1>Вход</h1>
      <div class="form-input">
        <input type="text" id="username" name="username" class="form-control" required placeholder=" " autocomplete="off" />
        <label for="username">Логин</label>
      </div>
      <div class="form-input">
        <input type="password" id="password" name="password" class="form-control" required placeholder=" " autocomplete="off"  />
        <label for="password">Пароль</label>
      </div>
      <button type="submit">Войти</button>
    </form>
  </body>
</html>