django-backend/src/Users/urls.py
from django.urls  import path

from .views import * 

from django.urls import path
from . import views

app_name = 'Users'

urlpatterns = [
    path('login/', views.user_login, name = 'login-main'),
    path('logout/', views.user_logout, name = 'logout-main'),
    path('register/', views.user_register, name = 'register'), 
    path('confirm-email/<uuid:token>/', views.confirm_email, name='confirm-email'),
    path('profile/', views.profile, name = 'profile'),
    path('edit/', views.edit_profile, name = 'profile-edit')
    
]

django-backend/src/core/api/urls.py
from django.urls import path, include, re_path
from . import views

urlpatterns = [
    path('subjects/', views.SubjetListView.as_view()),
    path('subjects/<int:pk>', views.SubjectDetailView.as_view()),
    path('subjects/create', views.SubjectCreateView.as_view()),
    path('subjects/update/<int:pk>', views.SubjectUpdateView.as_view()),
    path('auth/', include('djoser.urls')), 
    re_path(r'^auth/', include('djoser.urls.authtoken')),
]

django-backend/src/core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.FilmView.as_view(), name = "home"),
    path('search/', views.Search.as_view(), name='search'), 
    path('filter/', views.Filtr, name='filter'),
    path('search_navbar/', views.search_navbar, name = 'search_navbar'),
    path('films/<int:kinopoisk_id>/', views.film, name = 'film'),
    path('watch-later/<int:kinopoisk_id>/', views.watch_later, name = 'watch_later'),
    path('films-watch/', views.Film_watch , name='films-watch'),
    path('add-comment/<int:kinopoisk_id>/', views.add_comment, name='add_comment'),
    path('remove-comment/<int:kinopoisk_id>/<int:comment_id>',  views.remove_comment, name='remove_comment')

] 

django-backend/src/online_streaming/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('Users.urls')),
    path('api/', include('core.api.urls')),
    path('', include('core.urls')),

    
]  + debug_toolbar_urls() 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root = settings.MEDIA_ROOT)

django-backend/src/core/models.py
from django.db import models
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from Users.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
class Genre(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name= "Жанр")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Country(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name= "Страна")

    def __str__(self) -> str:
        return self.name

    class Meta:
        verbose_name = "Страна"
        verbose_name_plural = "Страны"


class Films(models.Model):
    TYPE_CHOOSE = [
        ("FILM", 'Фильмы'),
        ("TV_SERIES", 'Сериалы')
    ]


    title = models.CharField(max_length=255, verbose_name='Название фильма')
    short_description = models.CharField(max_length=255, verbose_name='Короткое описание', blank=True, null=True)
    description = models.TextField(verbose_name='Описание фильма', blank=True, null=True)
    kinopoisk_id = models.PositiveIntegerField(verbose_name='ID в кинопоиске')
    image_url = models.ImageField(upload_to="images", verbose_name="Обложка")
    years = models.PositiveIntegerField(verbose_name='Год выпуска')
    fees = models.PositiveBigIntegerField(verbose_name='Сборы', blank=True, null=True)
    budget = models.PositiveBigIntegerField(verbose_name='Бюджет фильма', blank=True, null=True)
    country = models.ManyToManyField(Country, verbose_name='Страна')
    grade = models.DecimalField(max_digits=3, decimal_places=1, max_length=5, verbose_name='Оценка фильма', default=0)
    duration = models.PositiveIntegerField(verbose_name='Продолжительность фильма', null= True)
    genres = models.ManyToManyField(Genre, verbose_name='Жанры')
    type = models.CharField(max_length=255, verbose_name='Тип фильма', choices=TYPE_CHOOSE)

    image_thumbnail = ImageSpecField(source='image_url',
                                     processors=[ResizeToFill(180,270)],
                                     format='JPEG',
                                     options={'quality':85},)
    
    image_large = ImageSpecField(source='image_url',
                                     processors=[ResizeToFill(280,420)],
                                     format='JPEG',
                                     options={'quality':85},)
                                         
    @property
    def get_image_url(self):
        return self.image_thumbnail.url
    

    @classmethod 
    def get_type(cls, type):
        for i in cls.TYPE_CHOOSE:
            if i[1] == type:
                return i[0]
            else:
                continue
        return None 

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name = 'Фильм'
        verbose_name_plural = 'Фильмы'


class Watch_later(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ManyToManyField(Films)
    add_data = models.DateTimeField(auto_now_add=True)


class Comments(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    film = models.ForeignKey(Films, on_delete=models.CASCADE)
    body = models.TextField(max_length=250)
    created_on = models.DateTimeField(auto_now_add=True) 
    grade = models.PositiveIntegerField(default=0, validators=[MinValueValidator(1), MaxValueValidator(5)])
    class Meta():
        ordering = ['created_on']

django-backend/src/core/forms.py
from django import forms 
from .models import Comments

class Comment(forms.ModelForm):
    class Meta:
        model = Comments
        fields = [
            'body',
            'grade',
        ]

django-backend/src/core/api/views.py
from rest_framework import generics
from ..models import Films
from .serializers import SubjectSerializer, SubjectSerializer_Detail
from rest_framework.permissions import IsAdminUser, IsAuthenticated

class SubjetListView(generics.ListAPIView):
    queryset = Films.objects.all()
    serializer_class = SubjectSerializer

class SubjectDetailView(generics.RetrieveAPIView):
    queryset = Films.objects.all()
    serializer_class = SubjectSerializer_Detail


class SubjectCreateView(generics.CreateAPIView):
    queryset = Films.objects.all()
    serializer_class = SubjectSerializer_Detail
    permission_classes = [IsAdminUser, ]

class SubjectUpdateView(generics.RetrieveUpdateAPIView):
    queryset = Films.objects.all()
    serializer_class = SubjectSerializer_Detail
    permission_classes = [IsAdminUser, ]

django-backend/src/core/views.py
from django.views.generic.list import ListView
from .models import Films, Genre, Country, Watch_later, Comments
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from .forms import Comment
from django.core.exceptions import PermissionDenied


class FilmView(ListView):
    template_name = 'index.html'
    queryset = Films.objects.order_by('?')
    context_object_name = 'items'
    paginate_by = 16

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all()
        context['country'] = Country.objects.all()
        return context

    def get_queryset(self):
        return super().get_queryset()
def users_liked_songs(request):
    favorites = Profile.objects.prefetch_related('liked_sonks').get(user=request.user)
    return render(request, 'liked_songs.html', {'favorites':favorites})

@login_required
def Film_watch(request):
    obj = Watch_later.objects.prefetch_related('film').get(user=request.user)
    return render(request, 'films_watch.html', {'items': obj.film.all()})

def film(request, kinopoisk_id):
    comments = Comments.objects.none()  
    try:
        film_item = Films.objects.get(kinopoisk_id=kinopoisk_id)
        comments = Comments.objects.filter(film=film_item)
    except Films.DoesNotExist:
        pass
    
    watch = 'Смотреть позже'    
    if request.user.is_authenticated:    
        if Watch_later.objects.filter(user=request.user, film=film_item).exists():
            watch = "Убрать из списка"
        else:
            watch = "Смотреть позже"

    return render(request, 'detail_film.html', {'item': film_item, 'watch': watch, 'comments': comments})


class Search(ListView):
    paginate_by = 18
    model = Films
    template_name = 'index.html'
    context_object_name = 'items'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['genre'] = Genre.objects.all()
        context['country'] = Country.objects.all()
        return context

    def get_queryset(self):
        query = Films.objects.all()
        return filter_films(self.request, query)


def filter_films(request, query):
    if request.method == 'GET':
        url_parameter = request.GET.get('q', '')
        genre = request.GET.get('genre', '')
        country = request.GET.get('country', '')
        type = Films.get_type(request.GET.get('type', ''))

        if type:
            query = query.filter(type=type)
        if url_parameter:
            query = query.filter(title__istartswith=url_parameter)
        if genre:
            query = query.filter(genres__name=genre)
        if country:
            query = query.filter(country__name=country)

    return query


def Filtr(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        if request.method == 'GET':
            query = Films.objects.all()
            query = filter_films(request, query)
            data = [
                {
                    'kinopoisk_id': film.kinopoisk_id,
                    'title': film.title,
                    'years': film.years,
                    'get_image_url': film.get_image_url
                }
                for film in query
            ]
            return JsonResponse({'context': data}, status=200)


def search_navbar(request):
    if request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        if request.method == 'GET':
            query = request.GET.get('q', '')
            films = Films.objects.filter(title__istartswith=query)[:5] if query else Films.objects.none()
            data = [
                {
                    'kinopoisk_id': film.kinopoisk_id,
                    'title': film.title,
                    'years': film.years,
                    'get_image_url': film.get_image_url
                }
                for film in films
            ]
            return JsonResponse({'context': data}, status=200)


def watch_later(request, kinopoisk_id):
    if request.user.is_authenticated:
        try:
            film = Films.objects.get(kinopoisk_id=kinopoisk_id)
            obj, created = Watch_later.objects.get_or_create(user=request.user)
            if film in obj.film.all():
                obj.film.remove(film)
            else:
                obj.film.add(film)
        except Films.DoesNotExist:
            pass

    return redirect('film', kinopoisk_id=kinopoisk_id)

@login_required
def add_comment(request, kinopoisk_id):
    film = get_object_or_404(Films, kinopoisk_id=kinopoisk_id)    
    if request.method == 'POST':
        form = Comment(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.film = film
            comment.user = request.user
            comment.save()
            return redirect('film', kinopoisk_id=kinopoisk_id) 
    else:
        form = Comment()
    return render(request, 'detail_film.html', {"form":form, 'item':film})


@login_required
def remove_comment(request, kinopoisk_id, comment_id):
    comment = get_object_or_404(Comments, pk = comment_id)
    if comment.user != request.user:
        raise PermissionDenied("Вы можете удалять только свои комментарии.")
    else:
        comment.delete()
        return redirect('film', kinopoisk_id=kinopoisk_id)

django-backend/src/core/templates/detail_film.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{ item.title }}</title>
  <link rel="stylesheet" href="{% static 'css/styles_detail_film.css' %}">
</head>
<body>
  <div class="navbar">
    <div class="navbar-container">
        <form id="filter-form" action="{% url 'search' %}" method="get">
            <input name="q" type="text" placeholder="Search" class="search-bar" value="{{ request.GET.q }}" autocomplete="off">
        </form>
        <div class="header-links">
            {% if request.user.is_authenticated %}
                <p>{{ request.user }}</p>
                <a href="{% url 'Users:logout-main' %}" class="header_logout">Выйти</a> 
            {% else %}
                <a href="{% url 'Users:login-main' %}" class="header_login">Войти</a>
                <a href="{% url 'Users:register' %}" class="header_register">Регистрация</a>
            {% endif %}
        </div>
    </div>
    <div id="searchResults" class="navbar-movie-list results" style="display: none;">
        <ul class="movie-list">
            <li class='movie'><p>Фильмы и сериалы</p></li>
        </ul>
    </div>
</div>

    <div class="navbar-left"> 
        <a href="{% url 'home' %}"><img src="{% static 'img/home.svg' %}" class="navbar-left-img"></a>
        <a href = "{% url 'films-watch' %}"><img src="{% static 'img/clock.svg' %}" class="navbar-left-img"></a>
    </div>
</div>
  <div class='container'>
    <div class="poster">
      <script> console.log("{{ item.image_url.url }}", "{{item.image_url}}")</script>

      <img src="{{ item.image_large.url }}" alt="{{ item.title }} poster"> 
    </div> 
    <div class="content">

      <h1>{{ item.title }}</h1>
      <p>{{ item.short_description }}</p>
      <div class="info-detail">
        <h2>О фильме</h2>
        <table>
          <tr>
            <td>Год производства</td>
            <td>{{ item.years }}</td>
          </tr>
          <tr>
            <td>Страна</td>
            <td>{% for country in item.country.all %}{{ country.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
          </tr> 
          <tr>
            <td>Жанр</td>
            <td>{% for genre in item.genres.all %}{{ genre.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
          </tr> 
          <tr>
            <td >Бюджет фильма</td>
            <td class = 'number_money'>{{ item.budget|default_if_none:'неизвестно' }}  </td>
          </tr>
          <tr>
            <td>Сборы в мире</td>
            <td class = 'number_money'>{{ item.fees|default_if_none:'неизвестно' }}</td>
            <script>
              document.addEventListener('DOMContentLoaded', function () {
                let moneyElements = document.querySelectorAll('.number_money');
      
                moneyElements.forEach(function (element) {
                  let valueText = element.textContent.trim();
                  let value = parseInt(valueText);
            
                  if (!isNaN(value)) {
                    let formatted = value.toLocaleString("en-US", {
                      style: 'currency', currency: "USD", minimumFractionDigits: 0
                    });
                    element.textContent = formatted;
                  } else {
                    console.log("Value is not a number:", valueText);
                  }
                });
              });
            </script>
          </tr>
          <tr>
            <td>Продолжительность фильма</td>
            <td>{{ item.duration }} мин</td>
          </tr>
        </table>
      </div>
      <div class="kinobox_player"></div>
      <div><a href="{% url 'watch_later' item.kinopoisk_id %}"> {{watch}}</a>  </div>
      <div class='container-comments'>
        <form action='{% url "add_comment" item.kinopoisk_id %}' method='POST', id='rating-form'>
          {% csrf_token %}
          <p>Рейтинг:</p>
          <div class="rating-stars">
            <input type="radio" id="star5" name="grade" value="5"><label for="star5">&#9733;</label>
            <input type="radio" id="star4" name="grade" value="4"><label for="star4">&#9733;</label>
            <input type="radio" id="star3" name="grade" value="3"><label for="star3">&#9733;</label>
            <input type="radio" id="star2" name="grade" value="2"><label for="star2">&#9733;</label>
            <input type="radio" id="star1" name="grade" value="1"><label for="star1">&#9733;</label>
        </div>
        <br>
        <p>Комментарий:</p>
        <textarea id='comment' name='body' rows='4' cols='50'
                  required placeholder='Напишите свой комментарий' class="comment-text"></textarea>
        <button type='sumbit'>Отправить</button>
        </form>
      </div>
      <div> 
        {% for comment in comments %}
        <p> {{comment.user}} написал:{{comment.body}} , {{comment.grade}}  ЗВЁЗД</p>
        {% if comment.user == request.user %}
        <a href="{% url 'remove_comment' item.kinopoisk_id comment.pk %}">Удалить</a>
    {% endif %}
        {% endfor %}
      </div>
    </div>
  </div>

  <script src="https://kinobox.tv/kinobox.min.js"></script>
  <script>
    kbox('.kinobox_player', {
      search: {
        kinopoisk: "{{ item.kinopoisk_id }}"
      }
    });
  </script>
</body>
</html>

django-backend/src/core/templates/films_watch.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Смотреть позже</title>
  <link rel="stylesheet" href="{% static 'css/styles_index.css' %}">
</head>
<body>
  <div class="navbar">
    <div class="navbar-container">
        <form id="filter-form" action="{% url 'search' %}" method="get">
            <input name="q" type="text" placeholder="Search" class="search-bar" value="{{ request.GET.q }}" autocomplete="off">
        </form>
        <div class="header-links">
            {% if request.user.is_authenticated %}
                <p>{{ request.user }}</p>
                <a href="{% url 'Users:logout-main' %}" class="header_logout">Выйти</a> 
            {% else %}
                <a href="{% url 'Users:login-main' %}" class="header_login">Войти</a>
                <a href="{% url 'Users:register' %}" class="header_register">Регистрация</a>
            {% endif %}
        </div>
    </div>
    <div id="searchResults" class="navbar-movie-list results" style="display: none;">
        <ul class="movie-list">
            <li class='movie'><p>Фильмы и сериалы</p></li>
        </ul>
    </div>
</div>

    <div class="navbar-left"> 
        <a href="{% url 'home' %}"><img src="{% static 'img/home.svg' %}" class="navbar-left-img"></a>
        <a href = "{% url 'films-watch' %}"><img src="{% static 'img/clock.svg' %}" class="navbar-left-img"></a>
    </div>
</div>
  <div class="container">    
    <div class="main-content">
      <section class="banner">
        <h1>TV Shows</h1>
        <p>Watch past seasons of exclusive shows...</p>
      </section>
  
      <section class="shows-list">
        {% for item in items %}
        <div class="show-card">
          <a href="{% url 'film' item.kinopoisk_id %}" class='card-link'></a>  
          <img src="{{ item.image_thumbnail.url }}" alt="{{ item.title }}">
          <h3>{{ item.title }}</h3>
          <p>{{ item.years }}</p>
        </div>
        {% endfor %}
      </section>
      
    </div>
  </div>
</body>
<footer >
  Какая-то информация об авторском праве или может информация об авторе статьи?
</footer>
</html>

django-backend/src/core/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Streaming Service</title>
  <link rel="stylesheet" href="{% static 'css/styles_index.css' %}">
</head>
<body>
  <div class="navbar">
    <div class="navbar-container">
        <form id="filter-form" action="{% url 'search' %}" method="get">
            <input name="q" type="text" placeholder="Search" class="search-bar" value="{{ request.GET.q }}" autocomplete="off">
        </form>
        <div class="header-links">
            {% if request.user.is_authenticated %}
               <a href="{% url 'Users:profile' %}"> <p>{{ request.user }}</p> </a>
                <a href="{% url 'Users:logout-main' %}" class="header_logout">Выйти</a> 
            {% else %}
                <a href="{% url 'Users:login-main' %}" class="header_login">Войти</a>
                <a href="{% url 'Users:register' %}" class="header_register">Регистрация</a>
            {% endif %}
        </div>
    </div>
    <div id="searchResults" class="navbar-movie-list results" style="display: none;">
        <ul class="movie-list">
            <li class='movie'><p>Фильмы и сериалы</p></li>
        </ul>
    </div>
</div>

    <div class="navbar-left"> 
        <a href="{% url 'home' %}"><img src="{% static 'img/home.svg' %}" class="navbar-left-img"></a>
        <a href = "{% url 'films-watch' %}"><img src="{% static 'img/clock.svg' %}" class="navbar-left-img"></a>
    </div>
</div>
  <div class="container">    
    <div class="main-content">
      <section class="banner">
        <h1>TV Shows</h1>
        <p>Watch past seasons of exclusive shows...</p>
      </section>
        
      <section class="filters" >
        <div class='dropdown' >
          <div class='select' >
            <span class='selected'>Жанр</span>
            <div class='caret'></div>
          </div>
          <ul class='menu-genre'>
            {% for i in genre %}
            <li >{{i}}</li>
            {% endfor %}
          </ul>
        </div>
        <div class='dropdown' >
          <div class='select' >
            <span class='selected'>Страна</span>
            <div class='caret'></div>
          </div>
          <ul class='menu-country'>
            {% for i in country %}
            <li >{{i}}</li>
            {% endfor %}
          </ul>
        </div>
        <div class='dropdown' >
          <div class='select' >
            <span class='selected'>Тип</span>
            <div class='caret'></div>
          </div>
          <ul class='menu-type'>
            <li>Фильмы</li>
            <li>Сериалы</li>
          </ul>
        <script src="{% static 'js/menu.js' %}"></script>
        <script src = "{% static 'js/getfilms.js' %}"></script>
      </section>
  
      <section class="shows-list">
        {% for item in items %}
        <div class="show-card">
          <a href="{% url 'film' item.kinopoisk_id %}" class='card-link'></a>  
          <img src="{{ item.image_thumbnail.url }}" alt="{{ item.title }}">
          <h3>{{ item.title }}</h3>
          <p>{{ item.years }}</p>
        </div>
        {% endfor %}
      </section>
      
    </div>
  </div>
</body>
<footer >
  Какая-то информация об авторском праве или может информация об авторе статьи?
</footer>
</html>